import { afterEach,beforeEach,describe,expect,it,vi } from 'vitest';
const session=vi.hoisted(()=>({getSession:vi.fn()}));
vi.mock('../lib/supabase',()=>({supabase:{auth:session}}));
async function client(){vi.resetModules();vi.stubEnv('VITE_API_URL','http://127.0.0.1:3000/api/v1/');return import('../api/client');}
beforeEach(()=>{session.getSession.mockResolvedValue({data:{session:{access_token:'test-only-access-token'}}});});
afterEach(()=>{vi.unstubAllGlobals();vi.unstubAllEnvs();vi.clearAllMocks();});
describe('real API boundary',()=>{
 it('accepts JSON null for an empty latest telemetry result',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response('null')));const {request}=await client();expect(await request('/machines/test/latest')).toBeNull();});
 it('uses one configured base and sends the current bearer token',async()=>{const fetch=vi.fn().mockResolvedValue(new Response('{"items":[]}'));vi.stubGlobal('fetch',fetch);const {request}=await client();await request('/machines');expect(fetch.mock.calls[0][0]).toBe('http://127.0.0.1:3000/api/v1/machines');expect(fetch.mock.calls[0][1].headers.get('Authorization')).toBe('Bearer test-only-access-token');});
 it('rejects invalid JSON rather than pretending it is an empty dataset',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response('<html>wrong server</html>')));const {request}=await client();await expect(request('/machines')).rejects.toMatchObject({code:'INVALID_RESPONSE'});});
 it('preserves server validation details',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(JSON.stringify({error:{code:'VALIDATION_ERROR',message:'Invalid machine',details:[{path:'name',message:'Too short'}]}}),{status:422})));const {request}=await client();await expect(request('/machines')).rejects.toMatchObject({status:422,details:[{path:'name',message:'Too short'}]});});
 it('distinguishes unreachable services from timeouts',async()=>{const fetch=vi.fn().mockRejectedValue(new TypeError('Failed to fetch'));vi.stubGlobal('fetch',fetch);const {request}=await client();await expect(request('/machines')).rejects.toMatchObject({code:'NETWORK_ERROR'});fetch.mockRejectedValue(new DOMException('Timed out','TimeoutError'));await expect(request('/machines')).rejects.toMatchObject({code:'TIMEOUT'});});
 it('notifies the auth provider when the server rejects the session',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response('{"error":{"code":"UNAUTHENTICATED","message":"Expired"}}',{status:401})));const expired=vi.fn();window.addEventListener('urjaai:session-expired',expired);const {request}=await client();await expect(request('/machines')).rejects.toMatchObject({status:401});expect(expired).toHaveBeenCalledOnce();window.removeEventListener('urjaai:session-expired',expired);});
 it('does not send a token to a caller-provided absolute URL',async()=>{const fetch=vi.fn();vi.stubGlobal('fetch',fetch);const {request}=await client();await expect(request('https://wrong.invalid')).rejects.toMatchObject({code:'INVALID_PATH'});expect(fetch).not.toHaveBeenCalled();});
 it('rejects private Supabase keys in browser configuration',async()=>{const {isPublicSupabaseKey}=await import('../lib/config');expect(isPublicSupabaseKey('sb_secret_test')).toBe(false);const payload=btoa(JSON.stringify({role:'service_role'}));expect(isPublicSupabaseKey('header.'+payload+'.signature')).toBe(false);expect(isPublicSupabaseKey('sb_publishable_example')).toBe(true);});
});
