import { test,expect,type Page } from '@playwright/test';
import { mkdir,readFile } from 'node:fs/promises';
const api=process.env.TEST_API_URL ?? 'http://127.0.0.1:3100';
async function login(page:Page,email='owner@urjaai.test'){
 await page.goto('/login');await page.getByLabel('Work email').fill(email);await page.getByLabel('Password',{exact:true}).fill('Test-only-password-123');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).not.toHaveURL(/\/login/);
}
async function organization(page:Page,name:string){await expect(page).toHaveURL(/\/organization$/);await page.getByLabel('Organization name').fill(name);await page.getByLabel('Electricity tariff per kWh').fill('7.5');await page.getByRole('button',{name:'Save changes',exact:true}).click();await expect(page).toHaveURL(/\/dashboard$/);}
function localTime(date:Date){const pad=(v:number)=>String(v).padStart(2,'0');return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`;}
test('normal frontend → Express → PostgreSQL → populated dashboard and sharing',async({page,browser,request})=>{
 test.setTimeout(180000);
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
 await login(page);await organization(page,'TEST ONLY owner organization');
 await expect(page.getByText('Meet your next connected machine')).toBeVisible();
 await page.getByRole('link',{name:'Add machine',exact:true}).first().click();await page.getByLabel('Machine name').fill('TEST ONLY VMC integration');await page.getByLabel('Machine type').fill('CNC');await page.getByLabel('Location',{exact:true}).fill('TEST location');
 const creation=page.waitForResponse(r=>r.url()===api+'/api/v1/machines'&&r.request().method()==='POST');await page.getByRole('button',{name:'Create machine'}).click();const created=await creation;expect(created.status()).toBe(201);const machine=(await created.json()).id;
 await expect(page).toHaveURL(new RegExp('/machines/'+machine+'$'));await expect(page.getByText('The API returned an invalid response.')).toHaveCount(0);await expect(page.getByText('Awaiting telemetry')).toBeVisible();
 await page.getByRole('button',{name:'Calibration',exact:true}).click();
 for(const [label,value]of [['OFF upper threshold (W)','10'],['IDLE upper threshold (W)','100'],['Hysteresis (W)','2'],['State transition duration (seconds)','2'],['Sustained idle alert duration (seconds)','5']])await page.getByLabel(label,{exact:true}).fill(value);
 await page.getByRole('button',{name:'Save changes',exact:true}).click();await expect(page.getByText('Changes saved successfully')).toBeVisible();
 await page.getByRole('button',{name:'Device',exact:true}).click();await page.getByLabel('Device identifier').fill('TEST-BROWSER-ESP32');await page.getByLabel('Device name').fill('TEST ONLY device');const provision=page.waitForResponse(r=>r.url().endsWith(`/machines/${machine}/devices`)&&r.request().method()==='POST');await page.getByRole('button',{name:'Provision device'}).click();const device=await (await provision).json();
 await expect(page.getByText('Save this credential securely now')).toBeVisible();await page.getByRole('button',{name:'I’ve saved it — hide credential'}).click();
 const base=Date.now()-30000;
 for(const [seq,seconds,power,kwh]of [[1,0,50,10],[2,3,50,10.01],[3,10,50,10.02],[4,12,500,10.03],[5,15,500,10.04],[6,20,500,10.05]]){
  const result=await request.post(api+'/api/v1/device/telemetry',{headers:{Authorization:'Device '+device.credential},data:{device_id:'TEST-BROWSER-ESP32',timestamp:new Date(base+seconds*1000).toISOString(),sequence_number:seq,firmware_version:'TEST-BROWSER-ONLY',measurements:{voltage_v:230,current_a:power/230,power_w:power,energy_kwh:kwh,frequency_hz:50,power_factor:1}}});expect(result.status()).toBe(200);
 }
 const dashboardResponse=page.waitForResponse(r=>r.url()===api+'/api/v1/dashboard');await page.goto('/dashboard');const dashboard=await (await dashboardResponse).json();expect(dashboard.total_machines).toBe(1);expect(dashboard.running).toBe(1);expect(dashboard.energy_today_kwh).toBeCloseTo(0.05,5);expect(dashboard.estimated_cost).toBeCloseTo(0.375,5);
 await expect(page.getByRole('link',{name:'TEST ONLY VMC integration',exact:true})).toBeVisible();await expect(page.getByText('Running',{exact:true}).last()).toBeVisible();await page.getByText('View chart data as a table').click();await expect(page.getByRole('cell',{name:/500/}).first()).toBeVisible();
 await mkdir('../urjaai-integration/qa',{recursive:true});await page.screenshot({path:'../urjaai-integration/qa/populated-dashboard.png',fullPage:true});
 await page.goto(`/reports?machine_id=${machine}`);await page.getByRole('button',{name:'Generate report'}).click();await expect(page.getByRole('cell',{name:'TEST ONLY VMC integration'})).toBeVisible();const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Export CSV'}).click();const download=await downloadEvent;const csv=await readFile((await download.path())!,'utf8');expect(csv).toContain('TEST ONLY VMC integration');
 await page.goto('/settings');await page.getByRole('button',{name:'Notifications',exact:true}).click();await page.getByLabel('WhatsApp number').fill('+919999999999');await page.getByLabel('Receive WhatsApp notifications').selectOption('ON');const prefs=page.waitForResponse(r=>r.url().endsWith('/users/me/notifications')&&r.request().method()==='PUT');await page.getByRole('button',{name:'Save changes',exact:true}).click();expect((await prefs).status()).toBe(200);await page.reload();await page.getByRole('button',{name:'Notifications',exact:true}).click();await expect(page.getByLabel('WhatsApp number')).toHaveValue('+919999999999');await expect(page.getByLabel('Receive WhatsApp notifications')).toHaveValue('ON');await expect(page.getByText('Destination verification required')).toBeVisible();
 await page.goto(`/machines/${machine}?tab=Share`);await page.getByLabel('Listing title').fill('TEST ONLY shared VMC');await page.getByLabel('Public description').fill('Test-only capacity for integration verification.');const listingResponse=page.waitForResponse(r=>r.url().endsWith('/share/listings')&&r.request().method()==='POST');await page.getByRole('button',{name:'Save listing draft'}).click();const listing=(await (await listingResponse).json()).id;
 await page.goto('/share/'+listing);const start=new Date(Date.now()+25*3600000),end=new Date(Date.now()+27*3600000);await page.getByLabel('Start (your local time)').fill(localTime(start));await page.getByLabel('End (your local time)').fill(localTime(end));await page.getByRole('button',{name:'Save availability'}).click();await expect(page.getByRole('button',{name:'Preview & publish'})).toBeEnabled();await page.getByRole('button',{name:'Preview & publish'}).click();await page.getByRole('button',{name:'Confirm publication'}).click();await expect(page.getByRole('button',{name:'Pause listing'})).toBeVisible();
 const context=await browser.newContext();const other=await context.newPage();try{
  await login(other,'requester@urjaai.test');await organization(other,'TEST ONLY requester organization');await other.goto('/share/'+listing);await expect(other.getByRole('button',{name:'Pause listing'})).toHaveCount(0);await other.getByLabel('Start (your local time)').fill(localTime(start));await other.getByLabel('End (your local time)').fill(localTime(new Date(+start+3600000)));await other.getByLabel('Tell the owner what you need').fill('TEST ONLY booking');await other.getByRole('button',{name:'Send booking request'}).click();await expect(other.getByText('Changes saved successfully')).toBeVisible();
  await page.goto('/bookings');await page.getByRole('button',{name:'Accept',exact:true}).click();await page.getByRole('button',{name:'Confirm accept'}).click();await expect(page.getByText('Accepted',{exact:true})).toBeVisible();await other.goto('/bookings?view=sent');await expect(other.getByText('Accepted',{exact:true})).toBeVisible();
 }finally{await context.close();}
 const proof=await (await request.get('/__integration/proof')).json();expect(proof).toMatchObject({machines:1,telemetry:6,organizations:2,bookings:1});
 await page.goto('/admin');await expect(page.getByText('Administrator authorization required')).toBeVisible();
 if (!(await page.getByRole('button',{name:'Sign out',exact:true}).isVisible())) await page.getByRole('button',{name:'Open navigation'}).click();
 await page.getByRole('button',{name:'Sign out',exact:true}).click();await expect(page).toHaveURL(/\/login/);await page.goto('/dashboard');await expect(page).toHaveURL(/\/login/);expect(errors).toEqual([]);
});
test('unreachable API displays a recoverable error, not a fabricated empty result',async({page})=>{
 await login(page);await page.route(api+'/api/v1/machines?*',route=>route.abort('failed'));await page.goto('/machines');await expect(page.getByRole('alert')).toContainText('Unable to reach UrjaAI');await page.unroute(api+'/api/v1/machines?*');await page.getByRole('button',{name:'Retry',exact:true}).click();await expect(page.getByRole('link',{name:'TEST ONLY VMC integration',exact:true})).toBeVisible();
});
